name: Build & deploy
on: [push, workflow_dispatch]
env: 
  CI: false
jobs:
  test-unit: 
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
      - name: Test application
        run: npm run test
  test-component:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
      - name: Test application
        run: npx cypress run --component
  test-e2e: 
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
      - name: Test application
        run: | 
          (npm start) &
            pid=$!
          npx cypress run --e2e
  build:
    needs: [test-unit, test-component, test-e2e]
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
      - name: Test application
        run: npm run test
      - name: Lint application
        run: npm run lint
      - name: Build application
        run: npm run build
      - name: Deploy
        run: echo Deploying...
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3